### ISSUE TITLE
Starred lists

### ISSUE THREAD

**Issue by S0me1-dev** [haile01/github-starred-list#1]
Hello , is it possible to work with Lists of starred repos? 
I looking for a long time for possibilty to made an easy sort , or even semi-manual sorting of mine unlisted starred repos, cause doing it by hands - is hell hard. 
Maybe your tool can help with it? 

here is mine community issue wich is ingored same as api endpoint discussion 
https://github.com/orgs/community/discussions/147751#discussioncomment-11678159

thanks

**Comment by nhtlongcs** [comment]
Yes, its can. Please read the instructions carefully and verify its yourself.

**Comment by S0me1-dev** [comment]
hmm . seems not all so easy 
my current mission is to made next
-- i have a lot of starred repos. but some of em not in any list.
-- need to send all unlisted starred repos to list called *unsorted* 
i made a mix of simple api usage + your tool but still no succes. cause there is a *rock* to find wich repos are listed , wich not.

**Comment by haile01** [comment]
Hi @hastalamuerte 

Sorry for the late reply. It's true that this repo can't perform the action you're describing. 
For your information, we're making this script with only adding/removing repository feature in mind, so other actions to a star list such as viewing all repos inside a list is not implemented yet. I've just taken a look and seems like it's a hard thing to do without puppeteer as well, since it has pagination.

I'm very appreciate if you can come up with a solution and make a pull request to it.
Thanks
